name: 'Global Warming: Fact or Fiction?'
favicon: null
layout_spectrum: 0.4344800713006407
typography_spectrum: 0.9022175655700266
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9012964337598532
  lightness: 0.5230136597529054
  saturation: 0.12284685368649662
  rhythmicContrast: 0.8274293630383909
purpose: []
